events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # Web 管理后台
        location /admin/ {
            alias /usr/share/nginx/html/admin/;
            index index.html;
            try_files $uri $uri/ /admin/index.html;
        }

        # uni-app 移动端
        location /mobile/ {
            alias /usr/share/nginx/html/mobile/;
            index index.html;
            try_files $uri $uri/ /mobile/index.html;
        }

        # 后端接口代理
        location /backend/ {
            proxy_pass http://fastapi_backend:8000/; # 对应 docker-compose 中的服务名
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 根目录自动跳转到管理后台
        location / {
            return 301 /admin/;
        }
    }
}